name = "shovanch-com"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# Pages configuration
pages_build_output_dir = "./dist"

[vars]
# Environment variables can be added here
# UMAMI_HOST = "https://cloud.umami.is"
